-- ==============================================================================
-- KAUSHAL REFRIGERATION & INTERIOR: SUPABASE DATABASE & STORAGE SCHEMA
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Go to "SQL Editor" in the left sidebar.
-- 3. Click "New Query", paste this entire file, and click "Run".
-- ==============================================================================

-- 1. Create 'quotes' table for customer enquiries and quote requests
CREATE TABLE IF NOT EXISTS public.quotes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    requirement TEXT,
    notes TEXT,
    status TEXT DEFAULT 'NEW' CHECK (status IN ('NEW', 'CONTACTED', 'CLOSED'))
);

-- Enable Row Level Security (RLS) on quotes
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Allow anyone (public visitors) to submit quotes
DROP POLICY IF EXISTS "Allow public insert on quotes" ON public.quotes;
CREATE POLICY "Allow public insert on quotes" 
ON public.quotes 
FOR INSERT 
WITH CHECK (true);

-- Restrict reading quotes strictly to authenticated backend service role (Protects customer privacy)
DROP POLICY IF EXISTS "Allow read on quotes" ON public.quotes;
CREATE POLICY "Allow read on quotes" 
ON public.quotes 
FOR SELECT 
USING (auth.role() = 'service_role');


-- 2. Create 'gallery_items' table for dynamic photos & products
CREATE TABLE IF NOT EXISTS public.gallery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    type TEXT DEFAULT 'image',
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    sub_category TEXT,
    location TEXT,
    src TEXT NOT NULL,
    description TEXT,
    specs JSONB DEFAULT '[]'::jsonb
);

-- Enable RLS on gallery_items
ALTER TABLE public.gallery_items ENABLE ROW LEVEL SECURITY;

-- Allow public to view all gallery items (Safe read-only access)
DROP POLICY IF EXISTS "Allow public read on gallery_items" ON public.gallery_items;
CREATE POLICY "Allow public read on gallery_items" 
ON public.gallery_items 
FOR SELECT 
USING (true);

-- Restrict inserting new gallery items to authenticated backend service role only
DROP POLICY IF EXISTS "Allow insert on gallery_items" ON public.gallery_items;
CREATE POLICY "Allow insert on gallery_items" 
ON public.gallery_items 
FOR INSERT 
WITH CHECK (auth.role() = 'service_role');

-- Restrict deleting gallery items to authenticated backend service role only
DROP POLICY IF EXISTS "Allow delete on gallery_items" ON public.gallery_items;
CREATE POLICY "Allow delete on gallery_items" 
ON public.gallery_items 
FOR DELETE 
USING (auth.role() = 'service_role');


-- 3. Setup Supabase Storage Bucket for Gallery Images
-- Creates public bucket 'gallery-images' if it doesn't already exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('gallery-images', 'gallery-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies: Anyone can view gallery images
DROP POLICY IF EXISTS "Public Access to gallery-images" ON storage.objects;
CREATE POLICY "Public Access to gallery-images"
ON storage.objects FOR SELECT
USING (bucket_id = 'gallery-images');

-- Allow image uploads to gallery-images
DROP POLICY IF EXISTS "Allow uploads to gallery-images" ON storage.objects;
CREATE POLICY "Allow uploads to gallery-images"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'gallery-images');

-- Restrict image deletions from gallery-images to service role only
DROP POLICY IF EXISTS "Allow deletion from gallery-images" ON storage.objects;
CREATE POLICY "Allow deletion from gallery-images"
ON storage.objects FOR DELETE
USING (bucket_id = 'gallery-images' AND auth.role() = 'service_role');
